/*
  build-config.js
  Generates config.js from environment variables.

  Expected environment variables on Vercel:
    SUPABASE_MIENBAC_URL
    SUPABASE_MIENBAC_ANON
    SUPABASE_MIENNAM_URL
    SUPABASE_MIENNAM_ANON

  Run: `node build-config.js`
*/
const fs = require('fs');
const path = require('path');

function getEnv(name) {
  return process.env[name] || '';
}

const config = {
  MienBac: {
    url: getEnv('SUPABASE_MIENBAC_URL'),
    anonKey: getEnv('SUPABASE_MIENBAC_ANON'),
  },
  MienNam: {
    url: getEnv('SUPABASE_MIENNAM_URL'),
    anonKey: getEnv('SUPABASE_MIENNAM_ANON'),
  },
};

const outPath = path.resolve(process.cwd(), 'config.js');
const content = `// Generated by build-config.js — do not commit secrets to repo\n` +
  'window.__SUPABASE_CONFIG__ = ' + JSON.stringify(config, null, 2) + ';\n';

fs.writeFileSync(outPath, content, 'utf8');
console.log('Wrote', outPath);
