// Generated by build-config.js — do not commit secrets to repo
window.__SUPABASE_CONFIG__ = {
  "MienBac": {
    "url": "",
    "anonKey": ""
  },
  "MienNam": {
    "url": "",
    "anonKey": ""
  }
};
